name: doer
favicon: null
layout_spectrum: 0.1692899977788329
typography_spectrum: 0.1674024872481823
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.06873657018877566
  lightness: 0.1683677660766989
  saturation: 0.6484941090457141
  rhythmicContrast: 0.199790989048779
purpose: []
